name: Build Chromium 131 for Captive

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CHROMIUM_VERSION: "131.0.6778.264"
  SDK_URL: "https://downloads.openwrt.org/releases/24.10.0/targets/qualcommax/ipq807x/openwrt-sdk-24.10.0-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y zstd python3-pip ninja-build
        pip install gnpy

    - name: Download SDK
      run: |
        wget ${{ env.SDK_URL }} -O sdk.tar.zst
        unzstd sdk.tar.zst -o sdk.tar
        tar -xf sdk.tar
        echo "SDK_DIR=$(realpath openwrt-sdk-*)" >> $GITHUB_ENV

    - name: Generate Dynamic Makefile
      run: |
        mkdir -p ${{ env.SDK_DIR }}/package/chromium-captive
        cat << EOF > ${{ env.SDK_DIR }}/package/chromium-captive/Makefile
        include \$(TOPDIR)/rules.mk

        PKG_NAME:=chromium-captive
        PKG_VERSION:=${{ env.CHROMIUM_VERSION }}
        PKG_RELEASE:=1

        PKG_SOURCE:=chromium-\$(PKG_VERSION).tar.xz
        PKG_SOURCE_URL:=https://commondatastorage.googleapis.com/chromium-browser-official/
        PKG_HASH:=skip

        PKG_BUILD_DEPENDS:=python3/host libnss

        include \$(INCLUDE_DIR)/package.mk

        define Package/chromium-captive
          SECTION:=net
          CATEGORY:=Network
          TITLE:=Chromium Headless v${{ env.CHROMIUM_VERSION }}
          DEPENDS:=+libnss +libevent2-core
          URL:=https://www.chromium.org
        endef

        define Build/Configure
          [ ! -d \$(PKG_BUILD_DIR) ] && mkdir -p \$(PKG_BUILD_DIR)
          gn gen \$(PKG_BUILD_DIR)/out --args='\\
            use_headless=true \\
            is_debug=false \\
            target_os="linux" \\
            target_cpu="arm64" \\
            use_glib=false \\
            use_icu=false \\
            enable_mdns=false \\
            disable_file_support=true \\
            blink_enable_generated_code_formatting=false \\
            enable_reporting=false \\
            symbol_level=0'
        endef

        define Build/Compile
          ninja -C \$(PKG_BUILD_DIR)/out headless_shell
          \$(STRIP) --strip-all \$(PKG_BUILD_DIR)/out/headless_shell
        endef

        define Package/chromium-captive/install
          \$(INSTALL_DIR) \$(1)/usr/bin
          \$(INSTALL_BIN) \$(PKG_BUILD_DIR)/out/headless_shell \$(1)/usr/bin/chromium-captive
        endef

        \$(eval \$(call BuildPackage,chromium-captive))
        EOF

    - name: Build Chromium
      run: |
        cd ${{ env.SDK_DIR }}
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        echo "CONFIG_PACKAGE_chromium-captive=y" >> .config
        make defconfig
        make -j$(nproc) V=s

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: chromium-${{ env.CHROMIUM_VERSION }}
        path: ${{ env.SDK_DIR }}/bin/packages/qualcommax/ipq807x/chromium-captive_*.ipk
